[package]
name = "rust-3d"
version = "0.1.0"
authors = ["Baransu <sajgonek123@gmail.com>"]

[[bin]]
name = "rust-3d"

[dependencies.math]
path = "src/math"

[dependencies]
gl = "*"
glutin = "*"
nalgebra = "0.6.0"
time = "0.1.35"
