[package]
name = "opengl"
version = "0.1.0"
authors = ["Tomasz Cichocinski <tomaszcichocinski@gmail.com>"]
build = "build.rs"

[lib]
name = "opengl"
path = "lib.rs"

[dependencies]

[build-dependencies]
gl_generator = "0.14.0"
