[package]
name = "opengl"
version = "0.1.0"
authors = ["Baransu <sajgonek123@gmail.com>"]
build = "build.rs"

[lib]
name = "opengl"
path = "lib.rs"

[dependencies]

[build-dependencies]
gl_generator = "0.5.0"
